 services:
  backend:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: [ "node", "app.js" ]

    environment:
      
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Samamotdepass1
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"




